version: "3"
services:
  app:
    container_name: dev_next_ts_app
    build:
      context: ./
      dockerfile: Dockerfile.dev
    tty: true
    volumes:
      - ./:/var/www
    ports:
      - "3000:3000"
    networks:
      - dev_next_ts_network
  # storybook:
  #   container_name: dev_next_ts_storybook
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile.dev
  #   command: npm run storybook
  #   tty: true
  #   volumes:
  #     - ./:/var/www
  #   ports:
  #     - "6006:6006"
  #   networks:
  #     - dev_next_ts_network

networks:
  dev_next_ts_network:
    external: true
